# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lZAlrjEL3azxf8tZ8koCSINhBpU4UgEr
"""

import pandas as pd

df = pd.read_csv('/content/Lead Scoring.csv')

df.shape
df.head()
df.info()

df.isnull().sum().sort_values(ascending=False)

# Conversion Rate
print("Conversion Rate:", df['Converted'].mean()*100)

# Lead Source Performance
print(df.groupby('Lead Source')['Converted'].mean().sort_values(ascending=False))

# Lead Origin Performance
print(df.groupby('Lead Origin')['Converted'].mean().sort_values(ascending=False))

import matplotlib.pyplot as plt

df.groupby('Lead Source')['Converted'].mean().sort_values().plot(kind='barh')
plt.title('Conversion Rate by Lead Source')
plt.show()

df.to_csv('lead_scoring_cleaned.csv', index=False)

df.to_csv('lead_scoring_cleaned.csv', index=False)